### ISSUE TITLE
Cert Manager syntax

### ISSUE THREAD

**Issue by HristoA** [kontena/pharos-docs#220]
There is mistake of example syntax about **acme** part:
```yaml
addons:
  cert-manager:
    enabled: true
    # webhook:
    #   enabled: true
    # issuers:
    # - kind: ClusterIssuer
    #   metadata:
    #     name: le-issuer
    #   spec:
    #     acme:
    #         server: https://acme-staging-v02.api.letsencrypt.org/directory
    #         email: foo@bar.com
    #         privateKeySecretRef:
    #           name: le-issuer
    #         http01: {}
    # ca_issuer:
    #   enabled: false
    # extra_args: []
```
This is the right syntax.
